# Generated by Django 4.2.6 on 2023-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_default_expense_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Quantity"),
        ),
    ]
