# Generated by Django 4.2.6 on 2023-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_expense_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="voucher_file_url",
            field=models.URLField(blank=True, null=True, verbose_name="Voucher File URL"),
        ),
    ]
