# Generated by Django 4.2.7 on 2023-12-01 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_expense_voucher_file_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="voucher_file_url",
        ),
        migrations.CreateModel(
            name="VoucherFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "file_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True, verbose_name="File Id"
                    ),
                ),
                ("file_url", models.URLField(verbose_name="File URL")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher File",
                "verbose_name_plural": "Voucher Files",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="voucher_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.voucherfile",
                verbose_name="Voucher File",
            ),
        ),
    ]
